@Ledger.WebServer_HostAddress = http://localhost:5197

###
POST {{Ledger.WebServer_HostAddress}}/api/Tickets
Accept: application/json
Body: 
{
  "ticket": {
    "ticketId": 0,
    "ticketNumber": "string",
    "ticketDescription": "string",
    "ticketStatus": 0,
    "ticketPriority": 0,
    "ticketType": 0,
    "ticketCreatedDate": "2021-07-07T14:00:00.000Z",
    "ticketClosedDate": "2021-07-07T14:00:00.000Z",
    "ticketDueDate": "2021-07-07T14:00:00.000Z",
    "ticketAssignedTo": "string",
    "ticketCreatedBy": "string",
    "ticketUpdatedBy": "string",
    "ticketUpdatedDate": "2021-07-07T14:00:00.000Z",
    "ticketComments": [
      {
        "commentId": 0,
        "commentText": "string",
        "commentedBy": "string",
        "commentedDate": "2021-07-07T14:00:00.000Z",
        "ticketId": 0
      }
    ]
  }
}